### ISSUE TITLE
Invalid character range

### ISSUE THREAD

**Issue by brainysmurf** [tech4david/nano-highlight#12]
On Mac OS X 10.14.3 when I install with "make install" and run "nano /tmp/hi.py" I get the following error:

Error in /Users/adam.morris/.nano/syntax/ALL.nanorc on line 168: Bad regex "[!&|=/*+\-<>]|\<(and|or|is|isnt|not)\>": invalid character range

So I edited line 168 to be:

color red "[!&|=/*+<>-]|\<(and|or|is|isnt|not)\>"

Moving the hyphen to be the last character in the range avoids having to use the escape.

**Comment by valenfys** [comment]
Hi, this is no longer maintained as I no longer use Nano. Please use one of the maintained forks; these can be found at: https://github.com/davidbailey00/nano-highlight/network/members
