### ISSUE TITLE
export LANG=C make error message when using ALL.nanorc syntax

### ISSUE THREAD

**Issue by FadeMind** [tech4david/nano-highlight#5]
Hi
Great work with this fork You made.
I found an issue, when in terminal I set `LANG=C` env.
My default LANG is PL (polish).
When I set `export LANG=C` and open any file in nano I have error msg before open nano:

`[tomasz@arch ~]$ nano .bashrc`
`Error in /home/tomasz/.nano/syntax/ALL.nanorc on line 171: Bad regex "[!&|=/*+\-<>]|\<(and|or|is|isnt|not)\>": Invalid range end`
`Press Enter to continue starting nano.`
171 line of ALL.nanorc have

```
color red "[!&|=/*+\-<>]|\<(and|or|is|isnt|not)\>"
```

**Comment by eppfel** [comment]
I have the exact same error on my Pi with Raspbian 7 and my server with CentOS 6.7.
I have the LANG `de_DE.UTF-8` and `en_GB.UTF-8`, but on both systems I have: `perl: warning: Falling back to the standard locale ("C").`
@FadeMind How do you think the locales are related?
After commenting out the mentioned line, the error is gone. So, I guess it is an error in the RegEx.

**Comment by alex3o0** [comment]
I just change the regular expression in the specified line from this:

    [!&|=/*+-<>]|<(and|or|is|isnt|not)>

to this:

    [<>!&|=/*+-]|<(and|or|is|isnt|not)>

**Comment by mercury00** [comment]
Ah, good work!
