### ISSUE TITLE
nanorc.nanorc breaks syntax highlighting completely

### ISSUE THREAD

**Issue by eppfel** [tech4david/nano-highlight#6]
I access my Pi with Raspbian 7 and my server with CentOS 6.7 over SSH. Including ALL.nanorc throws no error (besides #5), but breaks other syntax highlightings (tested Javascript, JSON and HMTL).

If I include them separately, it works the moment I exclude `nanorc.nanorc`.

**Comment by mmaluff** [comment]
This happens to me too. Not sure if it's a bug with nanorc.nanorc or with nano itself.

**Comment by dohliam** [comment]
I can confirm that this issue exists on nano 2.2.6, but not 2.5.3. Excluding `nanorc.nanorc` as suggested above seems to fix the problem.
