### ISSUE TITLE
install on Mac OS-X 10.10 causes error message when launching nano

### ISSUE THREAD

**Issue by joaocc** [tech4david/nano-highlight#7]
Followed the instructions for `make install` and then added the following line to `~/.nanorc`

> include ~/.nano/syntax/ALL.nanorc

now, when I launch nano, I get this message

> Error in /Users/u/.nano/syntax/ALL.nanorc on line 168: Bad regex "[!&|=/*+-<>]|<(and|or|is|isnt|not)>": invalid character range

**Comment by Caerostris** [comment]
Quick fix: Delete `coffeescript.nanorc`, remove the word `coffeescript` from line 1 of the Makefile.
`make clean; make install BSDREGEX=1`

**Comment by ibrokemypie** [comment]
why does this fix it @Caerostris ?

**Comment by Caerostris** [comment]
@ibrokemypie The file `ALL.nanorc` is compiled from various syntax files by `make install`.
Line 168 in `ALL.nanorc` originally comes from the coffeescript syntax, which uses some character in a regex which macOS can't deal with. Thus, entirely removing the coffeescript syntax fixes the problem.
Obviously, the proper solution would be to modify the regex to work on macOS.

**Comment by alex3o0** [comment]
I get this error on Ubuntu to, I just change the regular expression in the specified line from this:

    [!&|=/*+-<>]|<(and|or|is|isnt|not)>

to this:

    [<>!&|=/*+-]|<(and|or|is|isnt|not)>

**Comment by valenfys** [comment]
Dear all,

I am no longer maintaining nano-highlight. Please switch to another version, such as YSakhno's fork: https://github.com/YSakhno/nanorc

Apologies for the lack of communication.
David

@alex3o0 @Caerostris @ibrokemypie @joaocc @eppfel @mmaluff @dohliam @FadeMind @mercury00
